require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 5

Metrics/ClassLength:
  Max: 200

Capybara/CurrentPathExpectation:
  Enabled: false # https://github.com/rubocop/rubocop-rspec/issues/1636