require:
  - rubocop-rspec
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 5

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 150
